name: OpenVirtualBook
main: openVirtualBook.OpenVirtualBook
version: 1.0
author: Jingyuan Ma
depend: [Multiverse-Core]
commands:
  ob:
    description: used to switch if allow to pvp
    usage: /ob
    permission-message: §c无权执行！
permissions: 
  openVirtualBook.op: 
    default: op
  openVirtualBook.player: 
    default: true