name: ScoreBoard
main: scoreBoard.ScoreBoard
version: 1.0
author: Jingyuan Ma
commands:
  score:
    description: ScoreBoard Commands
    usage: /score
    permission-message: §c无权执行！
permissions: 
  scoreBoard.op: 
    default: op
  scoreBoard.player: 
    default: true