name: CheckInSystem
main: checkInSystem.CheckInSystem
version: "1.1"
api-version: "1.14"
author: Jingyuan Ma
commands:
  qd:
    description: used to check in
    usage: /qd
    permission-message: §c无权执行！
permissions: 
  checkin.op: 
    default: op
  checkin.player: 
    default: true