name: PVPSwitch
main: pvpSwitch.PVPSwitch
version: 1.2
author: Jingyuan Ma
depend: [Citizens]
commands:
  pvp:
    description: used to switch if allow to pvp
    usage: /pvp
    permission-message: §c无权执行！
permissions: 
  pvpSwitch.op: 
    default: op
  pvpSwitch.player: 
    default: true
  pvpSwitch.bypass: 
    default: op