name: WorldBoss
main: com.peter.worldBoss.WorldBoss
version: '1.1.0'
api-version: '1.15'
author: Jingyuan Ma
depend:
  - DungeonsXL
softdepend:
  - PlaceholderAPI
commands:
  boss:
    description: world boss helper
    usage: /boss
    permission-message: §c无权执行！
permissions: 
  worldBoss.op:
    default: op