Points: 600
RecoverItem:
  ID: 266
  Point: 100
  Name: §2矿工玉米
  Lore: §a这是一瓶神奇的玉米%§a右键吃掉它可以增加100挖矿点数
  Recipe: 0-266-0-266-266-266-0-266-0
ToolsLimit: 257,270,274,278,285
Worlds: world,world_nether
Notify: true
world:
  BlockInfo: 14:10,15:5,56:30,129:50
  HeightUnlimit: 60
  RecoverPointByBreakingBlock:
    OnUse: false
    BlockInfo: 1:1,2:1
world_nether:
  BlockInfo: '89:10'
  HeightUnlimit: 80
  RecoverPointByBreakingBlock:
    OnUse: false
    BlockInfo: '87:1'