name: DailyQuest
main: dailyQuest.DailyQuest
version: '1.1'
api-version: '1.15'
author: Jingyuan Ma
depend:
  - Citizens
  - Vault
  - PeterUtil
  - LevelSystem
softdepend:
  - PlaceholderAPI
commands:
  rw:
    description: DailyQuest Commands
    usage: /rw
    permission-message: §c无权执行！
permissions: 
  dailyQuest.op: 
    default: op
  dailyQuest.player: 
    default: true
  dailyQuest.vip1:
    default: false
  dailyQuest.vip2:
    default: false
  dailyQuest.vip3:
    default: false