name: PeterHelper
main: peterHelper.PeterHelper
version: '1.2.0'
api-version: '1.15'
author: Jingyuan Ma
depend:
  - ItemsAdder
  - ArmorEquipEvent
  - LevelSystem
softdepend:
  - PlaceholderAPI
commands:
  ph:
    description: helper plugin
    usage: /ph
    permission-message: §c无权执行！
permissions: 
  peterHelper.op:
    default: op