name: ChatBubble
main: chatBubble.ChatBubble
version: '1.1'
api-version: '1.14'
author: Jingyuan Ma
depend: [HolographicDisplays]
commands:
  cb:
    description: ChatBubble Command
    usage: /cb
    permission-message: §c无权执行！
permissions: 
  chatBubble.op: 
    default: op
  chatBubble.color: 
    default: op