name: PeterUtil
main: peterUtil.PeterUtil
version: "1.0.2"
api-version: "1.14"
author: Jingyuan Ma
commands:
  peterutil:
    description: PeterUtil Commands
    usage: /peterutil
    permission-message: §c无权执行！