name: VipSystem
main: vipSystem.VipSystem
version: '1.2.1'
api-version: '1.15'
depend:
  - LuckPerms
  - PeterUtil
softdepend:
  - PlaceholderAPI
  - Vault
author: Jingyuan Ma
commands:
  vip:
    description: VipSystem Command
    usage: /vip
    permission-message: §c无权执行！
permissions: 
  VipSystem.op: 
    default: op
  VipSystem.player: 
    default: true
