name: BetterWeapon
main: betterWeapon.BetterWeapon
version: '1.0'
api-version: '1.15'
author: Jingyuan Ma
depend:
  - Vault
commands:
  qh:
    description: used to check in
    usage: /qh
    permission-message: §c无权执行！
permissions: 
  BetterWeapon.op: 
    default: op
  BetterWeapon.player: 
    default: true