name: BannedWords
version: 2.0
main:  me.kav.bannedwords.Main
commands:
   bw:
      description: BannedWords Root Command
      usage: /<command>
   hellohello:
      description: testing utils
      usage: /<command>