name: ClockGUI
main: clockGUI.ClockGUI
version: '1.3'
api-version: '1.14'
author: Jingyuan Ma
softdepend:
  - Dps
  - PlayerPoints
  - Vault
commands:
  clock:
    description: Clock Command
    usage: /clock
    permission-message: §c无权执行！
permissions: 
  clock.op: 
    default: op
  clock.player: 
    default: true
  clock.bypass: 
    default: op