name: Dps
main: dps.Dps
version: '1.5.0'
api-version: '1.14'
author: Jingyuan Ma
depend:
  - DungeonsXL
  - ScoreBoard
commands:
  dps:
    description: Dps Commands
    usage: /dps
    permission-message: §c无权执行！
permissions: 
  dps.op: 
    default: op
  dps.player: 
    default: true