name: ReportSystem
main: reportSystem.ReportSystem
version: 1.0
author: Jingyuan Ma
commands:
  jb:
    description: ReportSystem Command
    usage: /jb
    permission-message: §c无权执行！
  jy:
    description: ReportSystem Command
    usage: /jy
    permission-message: §c无权执行！
permissions: 
  reportSystem.op: 
    default: op
  reportSystem.player: 
    default: true