name: ServerBroadcast
main: serverBroadcast.ServerBroadcast
version: 1.1
author: Jingyuan Ma
commands:
  bc:
    description: used to broadcast
    usage: /bc
    permission: bc.bc
    permission-message: §c无权执行！
permissions: 
  bc.bc: 
    default: op 