name: AutoShutdown
main: net.stupendous.autoshutdown.AutoShutdownPlugin
version: 3.2.1-1.5.1
commands:
  autoshutdown:
    description: Interact with the AutoShutdown plugin
    usage: "Usage: '/autoshutdown help'"
  as:
    description: Interact with the AutoShutdown plugin
    usage: "Usage: '/as help'"
    