name: DungeonManager
main: com.peter.dungeonManager.DungeonManager
version: '1.0'
api-version: '1.15'
author: Jingyuan Ma
depend:
  - DungeonsXL
softdepend:
  - PlaceholderAPI
commands:
  dm:
    description: Dungeon Manager
    usage: /dm
    permission-message: §c无权执行！
permissions: 
  worldBoss.op:
    default: op