name: DungeonManager
main: com.peter.dungeonManager.DungeonManager
version: '1.2.1'
api-version: '1.15'
author: Jingyuan Ma
depend:
  - DungeonsXL
  - LevelSystem
  - Dps
softdepend:
  - PlaceholderAPI
commands:
  dm:
    description: Dungeon Manager
    usage: /dm
    permission-message: §c无权执行！
permissions:
  dungeonManager.op:
    default: op